name = "beauty-api-pages"
pages_build_output_dir = "dist"
compatibility_date = "2024-11-01"

[[d1_databases]]
binding = "DB"
database_name = "beauty-app"
database_id = "dd57c4d5-2ce3-47b6-9a7a-f02afada99d3"

[[kv_namespaces]]
binding = "SESSION_KV"
id = "fee75d402e0f47c581b9f5d6661fd7f7"

[vars]
ADMIN_USERNAME = "15961962243"
ADMIN_PASSWORD = "123456bn"
TAOBAO_APP_KEY = "35375517"
TAOBAO_PID = "mm_26868668_3430700405_116312800133"
