import os

path = r"pages-functions/functions/api/tier2/status.ts"

lines = []
lines.append('import type { FrameworkCallbackOptions } from "@cloudflare/workers-types";')
lines.append('import { requireAuth, callDeepSeekTier2 } from "../../_utils";')
lines.append('import type { Ctx } from "../../_utils";')
lines.append('')
lines.append('// GET /api/tier2/status?tier1ReportId=xxx 或 ?tier2Id=xxx')
lines.append('// 查询 tier2 报告生成状态，已就绪时返回内容')
lines.append('export const GET: FrameworkCallbackOptions["GET"] = async (context) => {')
lines.append('  const { request, env } = context;')
lines.append('  const user = await requireAuth(request, env);')
lines.append('  if (!user) {')
lines.append('    return new Response(JSON.stringify({ error: "未登录" }), {')
lines.append('      status: 401,')
lines.append('      headers: { "Content-Type": "application/json" },')
lines.append('    });')
lines.append('  }')
lines.append('')
lines.append('  const url = new URL(request.url);')
lines.append('  const tier1ReportId = url.searchParams.get("tier1ReportId");')
lines.append('  const tier2Id = url.searchParams.get("tier2Id");')
lines.append('')
lines.append('  // 如果传了 tier2Id，直接查询该条记录')
lines.append('  if (tier2Id) {')
lines.append('    const row = await env.DB.prepare(')
lines.append('      `SELECT id, generation_status, content, source_tier1_report_id FROM reports_tier2 WHERE id = ? AND user_id = ? LIMIT 1`')
lines.append('    ).bind(tier2Id, user.userId).first<any>();')
lines.append('')
lines.append('    if (!row) {')
lines.append('      return new Response(JSON.stringify({ error: "报告不存在或无权访问" }), {')
lines.append('        status: 404,')
lines.append('        headers: { "Content-Type": "application/json" },')
lines.append('      });')
lines.append('    }')
lines.append('')
lines.append('    // 兼容旧版：stale pending（旧异步改造前遗留）自动补触发生成')
lines.append('    if (row.generation_status === "pending" && row.content === \'{"status":"pending"}\') {')
lines.append('      const tier1Row = await env.DB.prepare(')
lines.append('        `SELECT report_data FROM reports_tier1 WHERE id = (SELECT source_tier1_report_id FROM reports_tier2 WHERE id = ? LIMIT 1)`')
lines.append('      ).bind(row.id).first<any>();')
lines.append('      if (tier1Row) {')
lines.append('        try {')
lines.append('          const tier1Report = JSON.parse(tier1Row.report_data) as Record<string, unknown>;')
lines.append('          const now = Math.floor(Date.now() / 1000);')
lines.append('          await env.DB.prepare(')
lines.append("            `UPDATE reports_tier2 SET generation_status = 'processing', updated_at = ? WHERE id = ?`")
lines.append('          ').bind(now, row.id).run();')
lines.append('          context.waitUntil(generateTier2Async(tier1Report, row.id, env));')
lines.append('          return new Response(JSON.stringify({ generationStatus: "processing", tier2ReportId: row.id }), {')
lines.append('            headers: { "Content-Type": "application/json" },')
lines.append('          });')
lines.append('        } catch { /* JSON 解析失败，保持原样返回 */ }')
lines.append('      }')
lines.append('    }')
lines.append('')
lines.append('    const result: any = { generationStatus: row.generation_status, tier2ReportId: row.id };')
lines.append('    if (row.generation_status === "ready" && row.content) {')
lines.append('      try { result.content = JSON.parse(row.content); } catch { result.content = null; }')
lines.append('    }')
lines.append('    return new Response(JSON.stringify(result), {')
lines.append('      headers: { "Content-Type": "application/json" },')
lines.append('    });')
lines.append('  }')
lines.append('')
lines.append('  // 兼容旧版：通过 tier1ReportId 查询')
lines.append('  if (!tier1ReportId) {')
lines.append('    return new Response(JSON.stringify({ error: "缺少 tier1ReportId 或 tier2Id" }), {')
lines.append('      status: 400,')
lines.append('      headers: { "Content-Type": "application/json" },')
lines.append('    });')
lines.append('  }')
lines.append('')
lines.append('  const row = await env.DB.prepare(')
lines.append('    `SELECT id, generation_status, content, source_tier1_report_id FROM reports_tier2 WHERE source_tier1_report_id = ? AND user_id = ? LIMIT 1`')
lines.append('  )')
lines.append('    .bind(tier1ReportId, user.userId)')
lines.append('    .first<any>();')
lines.append('')
lines.append('  if (row) {')
lines.append('    // 兼容旧版：stale pending（旧异步改造前遗留）自动补触发生成')
lines.append('    if (row.generation_status === "pending" && row.content === \'{"status":"pending"}\') {')
lines.append('      const tier1Row = await env.DB.prepare(')
lines.append('        `SELECT report_data FROM reports_tier1 WHERE id = ?`')
lines.append('      ).bind(row.source_tier1_report_id).first<any>();')
lines.append('      if (tier1Row) {')
lines.append('        try {')
lines.append('          const tier1Report = JSON.parse(tier1Row.report_data) as Record<string, unknown>;')
lines.append('          const now = Math.floor(Date.now() / 1000);')
lines.append('          await env.DB.prepare(')
lines.append("            `UPDATE reports_tier2 SET generation_status = 'processing', updated_at = ? WHERE id = ?`")
lines.append('          ').bind(now, row.id).run();')
lines.append('          context.waitUntil(generateTier2Async(tier1Report, row.id, env));')
lines.append('          return new Response(JSON.stringify({ generationStatus: "processing", tier2ReportId: row.id }), {')
lines.append('            headers: { "Content-Type": "application/json" },')
lines.append('          });')
lines.append('        } catch { /* JSON 解析失败，保持原样返回 */ }')
lines.append('      }')
lines.append('    }')
lines.append('')
lines.append('    const result: any = { generationStatus: row.generation_status, tier2ReportId: row.id };')
lines.append('    if (row.generation_status === "ready" && row.content) {')
lines.append('      try { result.content = JSON.parse(row.content); } catch { result.content = null; }')
lines.append('    }')
lines.append('    return new Response(JSON.stringify(result), {')
lines.append('      headers: { "Content-Type": "application/json" },')
lines.append('    });')
lines.append('  }')
lines.append('')
lines.append('  return new Response(JSON.stringify({ generationStatus: "not_found" }), {')
lines.append('    headers: { "Content-Type": "application/json" },')
lines.append('  });')
lines.append('};')
lines.append('')
lines.append('// wrangler v4 compatibility: alias for route discovery')
lines.append('export const onRequestGet = async (...args) => {')
lines.append('  return (GET as any)(...args);')
lines.append('};')
lines.append('')
lines.append('async function generateTier2Async(tier1Report: Record<string, unknown>, tier2Id: string, env: Ctx["env"]): Promise<void> {')
lines.append('  try {')
lines.append('    const tier2Content = await callDeepSeekTier2(tier1Report, env);')
lines.append('    if (tier2Content) {')
lines.append('      const now = Math.floor(Date.now() / 1000);')
lines.append('      await env.DB.prepare(')
lines.append("        `UPDATE reports_tier2 SET content = ?, generation_status = 'ready', updated_at = ? WHERE id = ?`")
lines.append('      ').bind(JSON.stringify(tier2Content), now, tier2Id).run();')
lines.append('      console.log(`[tier2/status] Auto-triggered generation succeeded for ${tier2Id}`);')
lines.append('    } else {')
lines.append('      const now = Math.floor(Date.now() / 1000);')
lines.append('      await env.DB.prepare(')
lines.append("        `UPDATE reports_tier2 SET generation_status = 'failed', updated_at = ? WHERE id = ?`")
lines.append('      ').bind(now, tier2Id).run();')
lines.append('      console.error(`[tier2/status] Auto-triggered generation failed for ${tier2Id}`);')
lines.append('    }')
lines.append('  } catch (e) {')
lines.append('    console.error(`[tier2/status] Auto-trigger exception for ${tier2Id}:`, e);')
lines.append('  }')
lines.append('}')

with open(path, "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")

print(f"Written {len(lines)} lines to {path}")
print("File size:", os.path.getsize(path), "bytes")
