lines = []
lines.append("const { chromium } = require(\"playwright\");")
lines.append("(async () => {")
lines.append("  const browser = await chromium.launch({ headless: true });")
lines.append("  const page = await browser.newPage();")
lines.append("  await page.goto(\"http://127.0.0.1:8788\");")
lines.append("  await page.evaluate(() => localStorage.setItem(\"session_token\",\"58a91a89-76c1-4474-85ce-98fb9c194802\"));")
lines.append("  console.log(\"=== NORMAL REPORT ===\");")
lines.append("  await page.goto(\"http://127.0.0.1:8788/report/t1-e2e-001\");")
lines.append("  await page.waitForTimeout(20000);")
lines.append("  const evalFn=(imgs)=>imgs.map(img=>({src:img.src,loaded:img.complete&&img.naturalWidth>0,nw:img.naturalWidth,nh:img.naturalHeight}));")
lines.append("  const img1=await page.$$eval(\"img\",evalFn);")
lines.append("  console.log(JSON.stringify(img1,null,2));")
lines.append("  console.log(\"=== EXTREME REPORT ===\");")
lines.append("  await page.goto(\"http://127.0.0.1:8788/report/t1-e2e-extreme\");")
lines.append("  await page.waitForTimeout(20000);")
lines.append("  const img2=await page.$$eval(\"img\",evalFn);")
lines.append("  console.log(JSON.stringify(img2,null,2));")
lines.append("  const urls=[...new Set([...img1,...img2].map(i=>i.src).filter(s=>s&&s.startsWith(\"http\")))];")
lines.append("  console.log(\"=== DIRECT URL CHECKS ===\");")
lines.append("  for(const u of urls){")
lines.append("    if(!u||u.startsWith(\"data:\"))continue;")
lines.append("    try{const t=await browser.newPage();await t.goto(u,{waitUntil:\"domcontentloaded\",timeout:15000}).catch(()=>{});await t.waitForTimeout(3000);")
lines.append("      const d=await t.evaluate(()=>document.querySelector(\"img\")?{found:true}:{found:false});")
lines.append("      console.log(\"  \"+u.substring(0,90)+\" dims=\"+JSON.stringify(d));await t.close();")
lines.append("    }catch(e){console.log(\"  \"+u.substring(0,90)+\" ERR:\"+e.message);}")
lines.append("  }")
lines.append("  await browser.close();")
lines.append("  console.log(\"=== DONE ===\");")
lines.append("})();")
open("test_report_images.js","w").write(chr(10).join(lines))
print("written")
