const { chromium } = require('playwright');
(async () => {
  const browser = await chromium.launch({headless:true, args:['--no-sandbox']});
  const page = await browser.newPage();
  page.on('pageerror', err => console.log('PAGE ERR:', err.message));
  await page.addInitScript(() => { localStorage.setItem('session_token','test-token-123'); });
  await page.route('**/api/reports/mine', r => r.fulfill({status:200,body:JSON.stringify([])}));
  await page.route('**/api/tier1/analyze', r => r.fulfill({status:200,body:JSON.stringify({reportId:'test-r-789',report:{faceShape:'圆脸',skinType:'干性'}})}));
  await page.route('**/api/tier1/validate*', r => r.fulfill({status:200,body:JSON.stringify({valid:true})}));
  await page.route('**/api/tier2/status*', r => r.fulfill({status:200,body:JSON.stringify({generationStatus:'not_found'})}));
  await page.route('**/api/config/**', r => r.fulfill({status:404,body:'{}'}));
  await page.goto('https://9db21bfb.beauty-api-pages.pages.dev/report',{waitUntil:'networkidle'});
  await page.waitForTimeout(3000);
  console.log('BEFORE:',(await page.evaluate(()=>document.body.innerText.substring(0,200))));
  await page.locator('button', {hasText: '选择照片'}).click();
  await page.waitForTimeout(500);
  const input = await page.$('input[type=file]');
  if(input) await input.setInputFiles('C:/Users/yao/Documents/ChatGPT/美妆app/photo.jpg');
  await page.waitForTimeout(8000);
  console.log('AFTER:',(await page.evaluate(()=>document.body.innerText.substring(0,600))));
  console.log('HAS_REPORT:', await page.evaluate(()=>document.body.innerText.includes('圆脸')));
  await browser.close();
})();
