const { chromium } = require('playwright');
const BASE = 'http://localhost:5174';
const PHONE = '13055326649';
const TOKEN = '8f4873ff-746d-4170-9308-90b106aea95a';
async function main() {
  const browser = await chromium.launch({ headless: true, args: ['--no-sandbox'] });
  const ctx = await browser.newContext();
  const page = await ctx.newPage();
  const urlLog = [];
  page.on('framenavigated', nav => {
    urlLog.push({ t: Date.now(), url: nav.url() });
    console.log('[URL ' + urlLog.length + '] ' + new Date().toISOString() + ' -> ' + nav.url());
  });
  console.log('=== TEST 1: Protected page without token ===');
  await page.goto(BASE + '/report?id=some-id', { waitUntil: 'domcontentloaded' });
  console.log('[URL after nav] ' + page.url());
  await page.waitForTimeout(1000);
  console.log('');
  console.log('=== TEST 2: Navigate with valid token ===');
  await page.goto(BASE + '/home', { waitUntil: 'domcontentloaded' });
  await page.evaluate((token) => { localStorage.setItem('session_token', token); }, TOKEN);
  await page.waitForTimeout(500);
  await page.goto(BASE + '/report?id=' + TOKEN.split('-')[0], { waitUntil: 'domcontentloaded' });
  console.log('[URL after nav] ' + page.url());
  await page.waitForTimeout(2000);
  console.log('');
  console.log('=== TEST 3: Navigate to /login with token set ===');
  await page.goto(BASE + '/login', { waitUntil: 'domcontentloaded' });
  console.log('[At login URL] ' + page.url());
  await page.waitForTimeout(1000);
  console.log('');
  console.log('=== TEST 4: Logout then check redirect ===');
  await page.evaluate(() => { localStorage.removeItem('session_token'); });
  await page.goto(BASE + '/report?id=' + TOKEN.split('-')[0], { waitUntil: 'domcontentloaded' });
  console.log('[After logout URL] ' + page.url());
  await page.waitForTimeout(1000);
  console.log('');
  console.log('=== URL CHANGE LOG ===');
  urlLog.forEach((u, i) => console.log('  [' + (i+1) + '] ' + new Date(u.t).toISOString() + ' ' + u.url));
  await page.screenshot({ path: 'test_output/test_login_flow.png', fullPage: true });
  console.log('');
  console.log('[Screenshot: test_output/test_login_flow.png]');
  console.log('');
  console.log('=== DONE ===');
  await browser.close();
}
main().catch(e => { console.error('[FATAL]', e.message); process.exit(1); });