name = "beauty-api-pages"
pages_build_output_dir = "dist"
compatibility_date = "2024-11-01"

[[d1_databases]]
binding = "DB"
database_name = "beauty-app"
database_id = "597322ae-1bef-45d5-90bf-7606c92c524c"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "R2_TEMP"
bucket_name = "beauty-temp"

[[r2_buckets]]
binding = "R2_PERM"
bucket_name = "beauty-perm"

[[kv_namespaces]]
binding = "SESSION_KV"
id = "9f3105f5547642b693452f5f740f8e2c"

[vars]
ADMIN_USERNAME = "15961962243"
ADMIN_PASSWORD = "123456bn"
TAOBAO_APP_KEY = "35375517"
TAOBAO_PID = "mm_26868668_3430700405_116312800133"
