const fs = require('fs');

const BT = '\x60';
const DL = '$' + '{';
const DR = '}';

const capturePath = 'C:/Users/yao/Documents/ChatGPT/美妆app/app/src/pages/Capture.jsx';
const tier1Path = 'C:/Users/yao/Documents/ChatGPT/美妆app/app/src/pages/Tier1Result.jsx';
const appPath = 'C:/Users/yao/Documents/ChatGPT/美妆app/app/src/App.jsx';

function write(path, lines) {
  const content = lines.join('\n') + '\n';
  fs.writeFileSync(path, content, 'utf8');
  console.log('Written ' + path + ': ' + content.length + ' bytes');
  return content;
}

// Capture.jsx
const capture = [];
capture.push("import { useState, useCallback, useRef } from 'react';");
capture.push("import { Camera, CameraResultType, CameraSource } from '@capacitor/camera';");
capture.push("import { BASE } from '../api.js';");
capture.push('');
capture.push('/* --- 常量 --- */');
capture.push('');
capture.push('const ANALYSIS_STEPS = [');
capture.push("  '分析脸型',");
capture.push("  '分析三庭五眼比例',");
capture.push("  '分析眉形',");
capture.push("  '分析眼型',");
capture.push("  '分析肤质',");
capture.push("  '分析五官对称度',");
capture.push('];');
capture.push('');
capture.push('const STEP_DELAYS = [0, 650, 1500, 1900, 2700, 3200];');
capture.push('const MIN_ANIM_DURATION_MS = 800;');
capture.push('');
capture.push('/* --- 辅助函数 --- */');
capture.push('');
capture.push('function fileToBase64(file) {');
capture.push('  return new Promise((resolve, reject) => {');
capture.push('    const reader = new FileReader();');
capture.push('    reader.onload = () => resolve(reader.result);');
capture.push('    reader.onerror = reject;');
capture.push('    reader.readAsDataURL(file);');
capture.push('  });');
capture.push('}');
capture.push('');
capture.push('async function callAnalyze(base64, token, signal) {');
capture.push("  const blob = await fetch(base64, { signal }).then((r) => r.blob());");
capture.push("  const form = new FormData();");
capture.push("  form.append('photo', blob, 'capture.jpg');");
capture.push("  const res = await fetch(BASE + '/tier1/analyze', {");
capture.push("    method: 'POST',");
capture.push("    headers: { Authorization: " + BT + "Bearer " + DL + "token" + DR + BT + " },");
capture.push('    body: form,');
capture.push('    signal,');
capture.push('  });');
capture.push("  if (!res.ok) throw new Error(" + BT + "请求失败: " + DL + "res.status" + DR + BT + ");");
capture.push('  return res.json();');
capture.push('}');
capture.push('');
capture.push('/* --- 导航（模块级）--- */');
capture.push('');
capture.push('function navigateHome() {');
capture.push("  window.history.pushState({}, '', '/home');");
capture.push('  window.location.reload();');
capture.push('}');
capture.push('');
capture.push('/* --- 主组件 --- */');
capture.push('');
capture.push('export default function Capture() {');
capture.push("  const [stage, setStage] = useState('select');");
capture.push('  const [preview, setPreview] = useState(null);');
capture.push('  const [error, setError] = useState(null);');
capture.push('  const [visibleCount, setVisibleCount] = useState(0);');
capture.push('  const [apiReady, setApiReady] = useState(false);');
capture.push('  const [apiError, setApiError] = useState(null);');
capture.push('  const [reportData, setReportData] = useState(null);');
capture.push('');
capture.push('  const controllerRef = useRef(null);');
capture.push('');
capture.push("  const token = typeof localStorage !== 'undefined' ? localStorage.getItem('session_token') : null;");
capture.push('');
capture.push('  const pickImage = useCallback(async (source) => {');
capture.push('    try {');
capture.push('      const result = await Camera.getPhoto({');
capture.push('        quality: 85,');
capture.push('        allowEditing: false,');
capture.push('        resultType: CameraResultType.DataUrl,');
capture.push('        source,');
capture.push('      });');
capture.push('      const dataUrl = result.dataUrl;');
capture.push("      if (!dataUrl) throw new Error('未获取到图片数据');");
capture.push("      setPreview(dataUrl);");
capture.push("      setStage('analyzing');");
capture.push('      startAnalysis(dataUrl);');
capture.push('    } catch (e) {');
capture.push('      setError(e.message);');
capture.push("      setStage('error');");
capture.push('    }');
capture.push('  }, []);');
capture.push('');
capture.push('  const handleFileInput = useCallback(async (e) => {');
capture.push("    const file = e.target.files?.[0];");
capture.push('    if (!file) return;');
capture.push('    try {');
capture.push('      const dataUrl = await fileToBase64(file);');
capture.push('      setPreview(dataUrl);');
capture.push("      setStage('analyzing');");
capture.push('      startAnalysis(dataUrl);');
capture.push('    } catch (e) {');
capture.push('      setError(e.message);');
capture.push("      setStage('error');");
capture.push('    }');
capture.push('  }, []);');
capture.push('');
capture.push('  const startAnalysis = useCallback((base64) => {');
capture.push('    setVisibleCount(0);');
capture.push('    setApiReady(false);');
capture.push('    setApiError(null);');
capture.push('    setReportData(null);');
capture.push('');
capture.push('    STEP_DELAYS.forEach((delay, i) => {');
capture.push('      setTimeout(() => setVisibleCount(i + 1), delay);');
capture.push('    });');
capture.push('');
capture.push('    const totalStepTime = STEP_DELAYS[STEP_DELAYS.length - 1] + 400;');
capture.push('    const minAnimEnd = totalStepTime + MIN_ANIM_DURATION_MS;');
capture.push('');
capture.push('    controllerRef.current?.abort();');
capture.push('    const controller = new AbortController();');
capture.push('    controllerRef.current = controller;');
capture.push('');
capture.push('    (async () => {');
capture.push('      try {');
capture.push('        const data = await callAnalyze(base64, token, controller.signal);');
capture.push('        setReportData(data.report);');
capture.push('        setApiReady(true);');
capture.push('      } catch (e) {');
capture.push("        if (e.name === 'AbortError') return;");
capture.push('        setApiError(e.message);');
capture.push('        setApiReady(false);');
capture.push('      }');
capture.push('    })();');
capture.push('');
capture.push('    setTimeout(() => {');
capture.push('      if (apiReady) {');
capture.push("        setStage('done');");
capture.push('      } else if (apiError) {');
capture.push("        setStage('error');");
capture.push('      } else {');
capture.push("        setStage('analyzing');");
capture.push('      }');
capture.push('    }, minAnimEnd);');
capture.push('  }, [token, apiReady, apiError]);');
capture.push('');
capture.push('  const handleRetry = useCallback(() => {');
capture.push('    if (!preview) return;');
capture.push('    controllerRef.current?.abort();');
capture.push("    setStage('analyzing');");
capture.push('    startAnalysis(preview);');
capture.push('  }, [preview, startAnalysis]);');
capture.push('');
capture.push('  const handleViewReport = useCallback(() => {');
capture.push("    window.history.pushState({ preview, reportData }, '', '/tier1-result');");
capture.push('    window.location.reload();');
capture.push('  }, [preview, reportData]);');
capture.push('');
capture.push("  if (stage === 'select') {");
capture.push('    return (');
capture.push('      <div className="capture-page">');
capture.push('        <div className="capture-header">');
capture.push('          <button className="capture-back-btn" onClick={navigateHome}>‹ 返回</button>');
capture.push('          <span className="capture-title">生成美妆报告</span>');
capture.push('        </div>');
capture.push('        <div className="capture-select-area">');
capture.push('          <p className="capture-hint">请上传一张正面清晰自拍，方便我们为你生成美妆建议</p>');
capture.push('          <div className="capture-actions">');
capture.push('            <button');
capture.push('              className="capture-action-btn capture-camera-btn"');
capture.push('              onClick={() => pickImage(CameraSource.Camera)}');
capture.push('            >');
capture.push('              <span className="capture-icon">📷</span>');
capture.push('              拍照');
capture.push('            </button>');
capture.push('            <button');
capture.push('              className="capture-action-btn capture-gallery-btn"');
capture.push('              onClick={() => pickImage(CameraSource.Photos)}');
capture.push('            >');
capture.push('              <span className="capture-icon">🖼</span>');
capture.push('              从相册选择');
capture.push('            </button>');
capture.push('            <label className="capture-action-btn capture-web-btn">');
capture.push('              <span className="capture-icon">📁</span>');
capture.push('              选择本地文件');
capture.push('              <input');
capture.push('                type="file"');
capture.push('                accept="image/*"');
capture.push('                capture="environment"');
capture.push('                className="capture-file-input"');
capture.push('                onChange={handleFileInput}');
capture.push('              />');
capture.push('            </label>');
capture.push('          </div>');
capture.push('        </div>');
capture.push('      </div>');
capture.push('    );');
capture.push('  }');
capture.push('');
capture.push('  return (');
capture.push('    <div className="capture-page">');
capture.push('      <div className="capture-header">');
capture.push('        <button className="capture-back-btn" onClick={navigateHome}>‹ 返回</button>');
capture.push('          <span className="capture-title">生成美妆报告</span>');
capture.push('      </div>');
capture.push('      {preview && (');
capture.push('        <div className="capture-preview-wrap">');
capture.push('          <img className="capture-preview-img" src={preview} alt="预览" />');
capture.push('        </div>');
capture.push('      )}');
capture.push("      {stage === 'error' && (");
capture.push('        <div className="capture-error">');
capture.push('          <div className="capture-error-icon">⚠️</div>');
capture.push("          <p className=\"capture-error-text\">{error || '分析失败，请稍后重试'}</p>");
capture.push('          <button className="capture-retry-btn" onClick={handleRetry}>重试</button>');
capture.push('        </div>');
capture.push('      )}');
capture.push("      {stage === 'analyzing' && (");
capture.push('        <div className="capture-analyzing">');
capture.push('          <ul className="capture-steps">');
capture.push('            {ANALYSIS_STEPS.map((label, i) => (');
capture.push('              <li');
capture.push('                key={i}');
capture.push("                className={" + BT + "capture-step " + DL + "i < visibleCount ? 'capture-step--visible' : ''" + DR + BT + "}");
capture.push('              >');
capture.push('                <span className="capture-step-check">');
capture.push("                  {i < visibleCount ? '✓' : '·'}");
capture.push('                </span>');
capture.push('                <span className="capture-step-label">{label}</span>');
capture.push('              </li>');
capture.push('            ))}');
capture.push('          </ul>');
capture.push("          {visibleCount >= ANALYSIS_STEPS.length && !apiReady && !apiError && (");
capture.push('            <p className="capture-pending-text">正在整理结果中...</p>');
capture.push('          )}');
capture.push('        </div>');
capture.push('      )}');
capture.push("      {stage === 'done' && reportData && (");
capture.push('        <div className="capture-done">');
capture.push('          <div className="capture-checkmark">✓</div>');
capture.push('          <p className="capture-done-title">分析完成</p>');
capture.push('          <p className="capture-done-sub">已为你生成专属美妆建议</p>');
capture.push('          <button className="capture-view-report-btn" onClick={handleViewReport}>');
capture.push('            查看报告');
capture.push('          </button>');
capture.push('        </div>');
capture.push('      )}');
capture.push('    </div>');
capture.push('  );');
capture.push('}');

write(capturePath, capture);
console.log('Has ${token}:', capture.join('\n').includes('${token}'));
console.log('Has ${res.status}:', capture.join('\n').includes('${res.status}'));
