const fs = require('fs');
const tier1Path = 'C:/Users/yao/Documents/ChatGPT/美妆app/app/src/pages/Tier1Result.jsx';
const lines = [];
lines.push("import { useContext } from 'react';");
lines.push("import { AuthContext } from '../context/AuthContext.jsx';");
lines.push("import RequireAuth from '../router/RequireAuth.jsx';");
lines.push("import { getCompliment } from './complimentMap.js';");
lines.push('');
lines.push('/**');
lines.push(' * Tier1Result — 一级分析结果页');
lines.push(' *');
lines.push(' * 数据来源：Capture.jsx 跳转时通过 window.history.pushState 传入 state');
lines.push(' *   state.preview     — 用户照片 base64');
lines.push(' *   state.reportData  — analyze.ts 返回的 report 对象');
lines.push(' */');
lines.push('');
lines.push('const RESULT_ITEMS = [');
lines.push("  { key: 'faceShape',        label: '脸型',         icon: '◎' },");
lines.push("  { key: 'skinType',         label: '肤质',         icon: '◉' },");
lines.push("  { key: 'eyebrowShape',     label: '眉形',         icon: '❖', placeholder: '待分析' },");
lines.push("  { key: 'eyeShape',         label: '眼型',         icon: '◐', placeholder: '待分析' },");
lines.push("  { key: 'threeFiveRatio',   label: '三庭五眼',     icon: '☰', placeholder: '待分析' },");
lines.push("  { key: 'symmetry',         label: '五官对称度',   icon: '⚖', placeholder: '待分析' },");
lines.push('];');
lines.push('');
lines.push('function navigateBack() {');
lines.push("  window.history.pushState({}, '', '/home');");
lines.push('  window.location.reload();');
lines.push('}');
lines.push('');
lines.push('function handleShareReport() {');
lines.push('  // TODO: 分享卡片图片生成 & 触发分享/解锁 tier2 逻辑');
lines.push("  console.log('[Tier1Result] 分享解锁进阶报告（占位）');");
lines.push("  alert('分享功能开发中，敬请期待 ✨');");
lines.push('}');
lines.push('');
lines.push('export default function Tier1Result() {');
lines.push('  const { token } = useContext(AuthContext);');
lines.push('');
lines.push('  const state = window.location.state || {};');
lines.push('  const photo = state.preview ?? null;');
lines.push('  const report = state.reportData ?? null;');
lines.push('');
lines.push('  const resolvedResults = RESULT_ITEMS.map((item) => {');
lines.push('    const value = item.placeholder ?? (report?.[item.key] ?? item.placeholder);');
lines.push('    const compliment = getCompliment(item.key, value);');
lines.push('    return { ...item, value, compliment };');
lines.push('  });');
lines.push('');
lines.push("  const highlightText = report?.suggestions?.[0] ?? '发现你的独特之美';");
lines.push("  const personaTags = ['温柔知性风', '清透裸妆感'];");
lines.push('');
lines.push('  return (');
lines.push('    <RequireAuth fallbackPath="/home">');
lines.push('      <div className="tier1-result-page">');
lines.push('        <div className="tier1-result-header">');
lines.push('          <button className="tier1-result-back-btn" onClick={navigateBack}>‹ 返回</button>');
lines.push('          <span className="tier1-result-title">你的美妆分析结果</span>');
lines.push('          <div className="tier1-result-header-spacer" />');
lines.push('        </div>');
lines.push('        <div className="tier1-result-hero">');
lines.push('          {photo ? (');
lines.push('            <img className="tier1-result-photo" src={photo} alt="你的照片" />');
lines.push('          ) : (');
lines.push('            <div className="tier1-result-photo-placeholder">📷</div>');
lines.push('          )}');
lines.push('          <div className="tier1-result-tags">');
lines.push('            {personaTags.map((tag, i) => (');
lines.push('              <span key={i} className="tier1-result-tag">{tag}</span>');
lines.push('            ))}');
lines.push('          </div>');
lines.push('        </div>');
lines.push('        <div className="tier1-result-section">');
lines.push('          <h2 className="tier1-result-section-title">分析结果</h2>');
lines.push('          <div className="tier1-result-grid">');
lines.push('            {resolvedResults.map((item) => (');
lines.push('              <div key={item.key} className="tier1-result-item">');
lines.push('                <span className="tier1-result-item-icon">{item.icon}</span>');
lines.push('                <div className="tier1-result-item-body">');
lines.push('                  <span className="tier1-result-item-label">{item.label}</span>');
lines.push('                  <span className="tier1-result-item-value">{item.value}</span>');
lines.push('                  <span className="tier1-result-item-compliment">— {item.compliment}</span>');
lines.push('                </div>');
lines.push('              </div>');
lines.push('            ))}');
lines.push('          </div>');
lines.push('        </div>');
lines.push('        <div className="tier1-result-section">');
lines.push('          <h2 className="tier1-result-section-title">✨ 你的亮点</h2>');
lines.push('          <div className="tier1-result-highlight-card">');
lines.push('            <p className="tier1-result-highlight-text">{highlightText}</p>');
lines.push('          </div>');
lines.push('        </div>');
lines.push('        <div className="tier1-result-cta">');
lines.push('          <button className="tier1-result-cta-btn" onClick={handleShareReport}>');
lines.push('            分享解锁进阶报告');
lines.push('          </button>');
lines.push('          <p className="tier1-result-cta-hint">分享后即可解锁进阶报告</p>');
lines.push('        </div>');
lines.push('      </div>');
lines.push('    </RequireAuth>');
lines.push('  );');
lines.push('}');

const content = lines.join('\n') + '\n';
fs.writeFileSync(tier1Path, content, 'utf8');
console.log('Written:', content.length, 'bytes');
console.log('Has getCompliment import:', content.includes(\"import { getCompliment }\"));
console.log('Has compliment span:', content.includes('tier1-result-item-compliment'));
